# System Set-Up
language: cpp

# install dependencies
addons:
  apt:
    packages:
      - cmake
      - libcfitsio3-dev
  homebrew:
    packages: &macos_packages
      - cmake
      - pkgconfig
      - cfitsio
    update: true

matrix:
  include:
    - os: linux
    - os: osx
      name: "macOS with GCC"
      osx_image: xcode10.2
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
        homebrew:
          packages:
            - gcc@7
            - *macos_packages
    - os: osx
      name: "macOS with AppleClang"
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
            - libomp
            - *macos_packages
    - os: osx
      name: "macOS with vanilla Clang"
      osx_image: xcode10.2
      env:
        - MATRIX_EVAL="export LDFLAGS="$LDFLAGS -L/usr/local/opt/llvm/lib" && export CPPFLAGS="$CPPFLAGS -I/usr/local/opt/llvm/include" && CC=/usr/local/opt/llvm/bin/clang && CXX=/usr/local/opt/llvm/bin/clang++"
      addons:
        homebrew:
          packages:
            - llvm
            - libomp
            - *macos_packages

before_install:
  - eval "${MATRIX_EVAL}"

# set up installation
install:
  - echo $LDFLAGS
  - echo $CPPFLAGS
  - mkdir build
  - cd build
  - cmake .. -DRUN_TESTS=OFF

# build package and install
script:
  - make install
  # - make test

# notification settings
notification:
  email: false
