# System Set-Up
language: cpp

branches:
  only:
    - master

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      name: "Linux Bionic"
      env:
        - CC=gcc-9
        - CXX=g++-9
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-9
            - g++-9
            - cmake
            - libcfitsio-dev
    - os: osx
      osx_image: xcode11.3
      language: shell
      name: "macOS 10.14 GCC"
      env:
        - CC=gcc-9
        - CXX=g++-9
      addons:
        homebrew:
          packages:
            - cmake
            - cfitsio
            - gcc@9
          update: true
    - os: osx
      osx_image: xcode11.3
      language: shell
      name: "macOS 10.14 AppleClang"
      addons:
        homebrew:
          taps: sfarrens/sf
          packages:
            - cmake
            - cfitsio
            - bigmac
          update: true

before_install:
  - mkdir build
  - cd build

install:
  - cmake .. -DBUILD_MSVST=ON
  - make

script:
  - make test
